
version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest

    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk add git && apk add lftp
      - checkout
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - checkout
      - run: ssh -p 21 enprod@exx1135.exxoss.net
      - run: lftp sftp://${DEPLOY_USER}:'${DEPLOY_PASS}'@${DEPLOY_PRODUCTION_HOST} -e "cd enprod; mirror -v -R --exclude .git/ --exclude .circleci/ --exclude node_modules ./ ./; quit"


workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master