# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "STUDIO COLIBRI Theme"
description = "A theme for Studio Colibri agency"
homepage = "https://studiocolibri.be"
tags = ["website", "responsive", "agency"]
features = []
min_version = 0.1

[author]
  name = "Studio Colibri"
  homepage = "https://github.com/studiocolibri"
