---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/projects
  label: Projets
  create: all
  match: "**/*"
  templates:
  - projet
- type: document
  path: content/_index.md
  label: Homepage
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
  templates:
  - team-members
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
  templates:
  - services
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.101.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.101.0
