---
label: Services
hide_body: false
fields:
- name: nom
  type: text
  config:
    required: false
  label: Nom
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: emoji
  type: text
  config:
    required: false
  label: emoji
pages:
- content/services/eco-conception.md
